### ISSUE TITLE
Teaching Philosophy 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#10]
I'd like to formalize this for the year. Comments very welcome! 

[Teaching Philosophy](https://github.com/LDSSA/wiki/wiki/Teaching-Philosophy)

**Comment by manuelfcreis** [comment]
Seems great @PedroGFonseca 

I would only add what I feel was one of the great aspects of the academy, the process oriented approach. By deconstructing what is complicated into logical steps (EDA -> Modelling -> ...) The academy gave a practical and effective approach to handle issues either academically or professionally.

I really felt that the practical world of Data Science was never far from what was taught and that proximity made it much easier to actually take on the hackathons and future projects.

***

On another note, I feel like it would be great to actually have some **artefacts** from each of these steps, i.e. A prototype of the Knowledge graph; A *guide* to remoteness; What is good data communication.

They wouldn't need to be extraordinarily complex, but indicative of what the academy is aiming towards.

**Comment by PedroGFonseca** [comment]
@manuelfcreis makes perfect sense to me. To recap, the action items would be: 

- [x] link up a prototype of a knowledge graph (we have [this one to show](https://docs.google.com/presentation/d/e/2PACX-1vSfbGq6yAa0YpBcQyAXjUvb9M7D4wuB33Tsb-6B9LFXXUI7jKBOieXrHNpAiJ5PQNLVLEIQJdruV2KU/pub?start=false&loop=false&delayms=3000&slide=id.g4cd686a742_0_490))
- [x] Add a part about the deconstruction into logical and digestable bits 
- [x] add examples of communication (I think we probably have some guide)

**Comment by PedroGFonseca** [comment]
Note: Did all of the above, @manuelfcreis let me know if any further changes are required.

**Comment by hershaw** [comment]
One small suggestion and then I'm totally cool to close this one:

In the "Deductive beats inductive" paragraph which is one of the most important ones, a relatable example would be great to include. I'd suggest adding the following paragraphs:

"For example, say that we are looking to teach calculus. We could first start with learning series, sequences, looking at a graph of y=x^2 in the abstract, learn the fundamental theorem of calculus, etc. Then after a few years of this you would learn how you to apply your newfound knowledge to the very real and important task of modeling the spread of infectious disease.

Or we could flip this around and start with the idea that we are learning how to model the spread of infectious disease and work back from there eventually ending up at the abstract fundamentals which will allow you to then apply it to other situations."

**Comment by PedroGFonseca** [comment]
Love it, and shall execute on it

**Comment by HugoDLopes** [comment]
@PedroGFonseca @hershaw  one of the things I sell to applicants and I think it is quite true is that we advocate focussing on teaching things that are **useful** in the short-term - things that are broadly used in the industry **and** close to state of the art (not the things that are used in the industry and should have been replaced 10 years ago). This differentiates us from universities where the curriculum stays the same for some decades.

**Comment by hershaw** [comment]
I think you can use what he said pretty much word for word. Maybe we can also put it in quotes with his picture right next to it as well :-)

**Comment by PedroGFonseca** [comment]
Accepted, and [altered accordingly](https://github.com/LDSSA/wiki/wiki/Teaching-Philosophy#9-practical-and-connected-to-the-real-world)

@HugoDLopes please confirm

**Comment by HugoDLopes** [comment]
@PedroGFonseca spot on!
