### ISSUE TITLE
Additional guidelines for job posting approval

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#11]
Pedro had the excellent idea of adding some more required context for job postings:

- How will the projects I work on align to business goals?
- Who will I be working with, and who would I report to?
- How is success measured in this role?  
- What is the nature of the data I'll be managing?
- How does the data science team collaborate with other departments?
- How is data collected at your company?
- What toolset do you use, and are you open to using new ones?
- What kind of tooling do you use to manage and interact with your compute resources? 

If we like these, we can add them to the [job posting approval process](https://github.com/LDSSA/wiki/wiki/Job-Posting-Approval-%5BWIP%5D#approval-process)

**Comment by PedroGFonseca** [comment]
I'm obviously pro these ideas, but would also suggest someone do some further research on posts about what questions to ask (this was a 5 minute thing).

**Comment by hershaw** [comment]
Just went through these and I really do think that they would be a good thing to add to the guidelines. I'm going to add them into the wiki.

**Comment by hershaw** [comment]
The page is updated, let me know if that looks okay @PedroGFonseca. I know that we should probably spend some more time to go through these, however since it's been a while without an update I think we should go with what we've got rather than leave this issue hanging for 6 months.

**Comment by PedroGFonseca** [comment]
Seems good, the only caveat being that in the [example](https://github.com/LDSSA/wiki/wiki/Job-Posting-Approval-%5BWIP%5D#an-example) the questions aren't actually answered

**Comment by PedroGFonseca** [comment]
Can be closed, methinks
