### ISSUE TITLE
LDSSA Prep Course

### ISSUE THREAD

**Issue by minhhoang1023** [LDSSA/forum#15]
After the two previous batches of LDSSA, we identified the importance of a preparation course (Prep course) for the Starter Academy, and therefore decided to launch it this time around. The Prep course aims to equip students with the required knowledge for the exam and for the Academy itself.

**Why:** 

- Even though we require no prior knowledge in Data Science, Python still represents a barrier for many people, most of which are women and non-Engineers. Hence, with the Prep course, more students from diverse backgrounds will be able to pass the exam and join the Academy. 

- Several former students mentioned that they had had a hard time grasping all of the materials during the three-day bootcamp. So this year we want to prepare them beforehand with all useful materials, making it easier to complete the Bootcamp as well as the entire Academy. 

**What:** A self-directed 1-month course covering useful materials for the Academy (e.g. Python, numpy, Git, etc.). We will use Dataquest as an online course provider - they have very good learning materials for beginners. 

**When:** The course will start on April 1st 2019 and end on May 1st 2019

**How**: Exact details on how the course works will be determined and disclosed shortly. In general,  we are trying to create a strict deadline and a great sense of community in order to motivate students to complete the course.

Let me know what you all think :)

**Comment by PedroGFonseca** [comment]
100% for it, and available to help with anything I can :)

**Comment by hershaw** [comment]
Let's go ahead and leave this issue open until we actually start the course.
