### ISSUE TITLE
The LDSA Parent Organization Charter

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#2]
[Here is the charter.](https://docs.google.com/document/d/1EDQF8lFZA0DYKhru57rxLI4d7s3ReiN90BFdjTHtP-Q/edit?usp=sharing)

We are taking the step of logically splitting up the organization so that there are two main entities. In the short term it won't make much practical difference but we hope that this positions us to have some more options in what we do in the coming batches.

Note that this charter is for the parent org and the Starters Academy charter is much more simple and covered [here](https://docs.google.com/document/d/1kQSYyhxYkYIxTXOb2PbQF8qZfGikFzy_nypathWPJ5E/edit?usp=sharing).

**Comment by manuelfcreis** [comment]
@hershaw I think it's great as it is, I just have the following comments:

1. I feel like it's missing a **Vision** for the Academy

2. > Excellence does not mean exclusive and the creation of a community isn’t limited to Data Science

    I think this is a great point and extremely important to generate a great community.

3. > Since assembly membership includes the right to vote

    Are all votes equal? I feel like it should be clarified.

**Comment by hershaw** [comment]
Great feedback @manuelfcreis thanks for taking the time. 

1. Honest question for you: What is the difference between a mission and a vision and what is missing that a vision would cover? I always struggle with this part so if you feel like something is missing, I would really like to hear about it.

3. Yes, all votes are equal, very much a good thing to be explicit about, thanks for catching it.

**Comment by manuelfcreis** [comment]
> 1. Honest question for you: What is the difference between a mission and a vision and what is missing that a vision would cover? I always struggle with this part so if you feel like something is missing, I would really like to hear about it.

For me the main difference is between an aspirational statement and a pragmatic one. While the mission is the objective and how to reach the objective the vision, in my opinion, is more about the underlying values and what we are aiming for with our mission. 

*I don't feel like it's essential to have a vision, but I tend to like explicit visions as they can make a more cohesive team*

> The Lisbon Data Science Academy exists to create and maintain a community of excellence, with the teaching and learning of Data Science at its core.

I guess what I feel is missing is the why behind _creating and maintaining a community_. An example so it can be a little clearer:

>Mission：
The mission of Make-A-Wish International is to grant the wishes of children with life-threatening medical conditions to enrich the human experience with hope, strength and joy.
>
>Vision：
We are dedicated to making every eligible child’s wish come true.

Another example:

> UMass Amherst Center for Data Science
>
>The mission of the Center is to facilitate the highest quality data science education, research and industrial collaboration.
>
>The vision is to greatly expand the capacity to implement data science research, industry collaborations, educational programming, and the availability of cutting-edge computational tools.

**Comment by hershaw** [comment]
Man this is really good. no reason to leave the underlying reason for the community without a definition.

**Comment by PedroGFonseca** [comment]
I suggest we close this as an issue, or give it a max time for comments

**Comment by hershaw** [comment]
To right. Been thinking a bit about it still and need to talk with you guys about it... I would like to keep it open as a reminder. Think that's okay or is it too dirty to leave an issue hanging around as a reminder?

**Comment by PedroGFonseca** [comment]
Nah, it be cool

**Comment by hershaw** [comment]
Just dropping in a note to say that I'm having several ongoing conversations about what the vision should be. Not sure when we'll be available for the next update but hopefully the conversations start to converge.
