### ISSUE TITLE
Project nudge 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#21]
**Context:** Our objective is to achieve at least a 1/3rd ratio of women in the Academy, without using the quotas.

**Initiative:** one of the initiatives to do this is for each of those who want to participate to “nudge” 4 women to sign up. This simply means that we take it upon ourselves to keep track of whether they take all of the steps, and remind/encourage them where necessary.

**How you can help**
To take part, you will simply need to do the following: 

1. Chose 4 women or more that may want to sign up 
2. Talk to them directly about the Academy
3. On the day before the sign up starts (May 3rd) remind them to sign up immediately after midnight, to secure their place in the queue 
4. On May 4th confirm that they have signed up, and politely remind them if they haven’t 
5. On May 9th, confirm that they have submitted the test, and encourage them if they haven’t 
6. Between May 9th and May 11th, make sure they ensure their place by paying before the deadline. 
7. If need be, repeat the above steps for wave 2 

Operational stuff: 
- We have a [Trello board](https://trello.com/b/ZRTIKxP6/project-nudge-gender-eq-initiative) to help “nudgers”. This is of course optional (and shouldn’t have any personal information), but can help to keep track of what is and isn’t working.
- Our baseline from last year shows that if 4 nudgers ensure 4 women each sign up, the Quota is already avoided!

**Comment by hershaw** [comment]
Count me in!

**Comment by dominguezmaria** [comment]
Nice! Not sure if I can do 4, but I'll definitely try!

**Comment by minhhoang1023** [comment]
Most of women I know don't know Python so I am convincing them to take part in the Prep course. So I highly doubt that I can make it to 4... But I'll do my best!

**Comment by jtascensao** [comment]
I will give it a try!
