### ISSUE TITLE
Wave 1 Retrospective

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#23]
So now that the Wave 1 test has been out in the world running for a bit, I've spoken to several students, reviewed the test with several instructors and we have started to come to the following consensus:

- The first wave test was too hard but that’s okay. Part of our mission is a commitment to excellence and this definitely pushed us in the right direction.
- We agree with we we can’t change any of the rules for the first wave. We talked about doing this but to do a good and fair job would just be too time consuming.
- We should send out a message admitting to everyone that we made the first wave a but too hard. In order to make up for it, if you take but don’t pass the test in the first wave, you can keep your place in line for the second wave.
- The second wave test will be easier or have a lower cutoff. 

We should communicate these points to the students before the end of the wave so that they can stay motivated enough to try again with Wave 2 in the case they didn't pass Wave 1.

Minh - Can you communicate this to the prep course students?
Carol and Jose - I think it would be good to send out an email, what do you think?

Just to wrap things up: We made Wave 1 too hard but I'm 100% okay with that. Last year we had people in the academy that struggled with basic python and we should avoid that. However, at the same time, we don't want to be an Academy of expert programmers that are trying to transition into Data Science. We want to be diverse and inclusive while at the same time holding to our commitment to excellence. Figuring out how to strike the balance is very difficult but it's gotta be done!

**Comment by PedroGFonseca** [comment]
I wrote this to try to avoid all doubts and clear edge cases:

--------------

Candidates from Wave 1 who took the test and failed will keep their application order after Wave 2 starts. That means that every such candidate will have priority over candidates from Wave 2. 

This means that: 
- Candidates from wave 1 who passed the test have priority over candidates from wave 1 who failed the test and passed it only in wave 2, regardless or their original application order. 
- Candidates who have not taken the test will not have any priority. They will simply need to apply again as part of wave 2. 
- The gender equality initiative still applies, and will do so in the new ranking order. 

After wave 2 is complete, students who passed the test will be in this order: 

A - Student from wave 1, who passed the test 1st time 
B - Student from wave 1, who failed the test during wave 1, and then passed it in wave 2 
C - Student from wave 2 who passed the test in wave 2

**Comment by rjna** [comment]
I've just finished the exam. Just barely passed, using the full 3 hours and I've done wave 1 and 2 from 2018 in under 40 mins with all tasks completed. This exam is way way harder!
