### ISSUE TITLE
Sam and Pedro gone for the weekend

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#24]
Soooooo, I'm getting married in a month and this weekend is the bachelor party (or "stag do", if you speak the strange island english). That means from Friday night until Monday morning I will not only be unavailable, but **entirely unable** to help with anything having to do with the Academy. You know what I mean.

So let's prepare ourselves for it!

- We need to close up Wave 1 and decide who is accepted into batch3 from this wave. There is a repo [here](https://github.com/LDSSA/girl-power-and-admissions) that has some code in it that may be used.
- There will be issues with matching people based upon the names. I think that @PedroGFonseca has some code somewhere to handle that. If he could add it to the girl-power-and-admissions repo. that would be great.
- This should be sent out on Friday night so that people have the entire weekend to pay.
- In the acceptance email that we send out to them, we need to ask them what ticket they are going to be under (student, professional, company) so that we know how much we will need to charge them.
- Get ready to open up Wave 2 by creating the test and setting the cutoff.

During today and tomorrow, I can help with the following:

- I'll work with Pedro to finish up the code that can be run to decide who gets in on this wave. Then, hopefully, it will be a matter of running it and generating a list of names.
- I'll talk with Ricardo about what form to send out and how to match up who paid with the current candidates.
- I'll work with Carol and Jose to make sure that we're good to go in terms of communication.

Am I missing anything else?? If I am, please tell me!

**Comment by PedroGFonseca** [comment]
![](http://m.memegen.com/2e2vd4.jpg)
