### ISSUE TITLE
Closing up Applications

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#25]
# WARNING

Much of the code that these numbers are based upon are still under review and applications have not closed yet. However, most of the big trends are unlikely to change.

### Looks good so far!

There's a preliminary list of who has been accepted so far and the number is 50! We have 50 people so far that have gone through the process (24 that have actually paid) and be accepted! So by Wednesday morning after the wave 2 payment period ends, I'm pretty sure that we'll be able to declare the applications process a victor. Not a flawless victory but a victory nonetheless :-)

### Lil analysis

We still have some hours left for people to take the test so it will change but there are a few pretty cool things to notice:

#### Not very many women

We only seem to have 8 women in so far. that's the same as last year and there aren't even enough women to have passed the test so as to use the quota. Again, let's see what happens by the end of the day but it doesn't look great so far. 

#### Lots of applications

We have had about 400 applications so far. Pretty sweet.

#### Filled up fast!

31 of the people accepted applied within the first hour we were open. thats pretty bananas, we more than filled up the course within a single hour. I think that it's probably due to a high level of engagement created by an excellent marketing and prep course efforts.

#### Experienced professionals

Over 50% of our applicants are working professionals. We have about 40% of our applicants looking to change their career. I wonder what other bootcamps like Le Wagon and Iron Hack have?

![image](https://user-images.githubusercontent.com/424192/57984777-ee948e00-7a56-11e9-9f0e-17ca1895fd6a.png)

### Give feedback!

So far I'm the only one that's seen most of the code for the application process. A review would very much be nice.

**Comment by hershaw** [comment]
Okay so I might have been jumping the gun with saying that 7 hours before closing the general trends would probably not change. Since I wrote that, we've had like 20 people finish the test.

Sorry about that, stay tuned!

**Comment by hershaw** [comment]
Also, let's hold out some hope that there are bugs in there that we just haven't found yes and the female numbers are wrong.

**Comment by hershaw** [comment]
Okay the applications really are still coming in. Looks like we'll need to use the Quota 5 times so far.

**Comment by hershaw** [comment]
So far we have a full 50 people in right now with an additional 31 people that passed but won't get a spot in the course. I think that last year we only had 1 or 2 people not get in because we reached capacity. 

This is very flattering but also kind of a bummer. 31 people that cared enough to at least go through the test and pass it that won't get into the academy this time around. I think it might be time to try to get another crew to fork us in the near future. If we grow like this again next year there will just be too many people asking for a DS education and not getting it that it can't be ignored.

**Comment by hershaw** [comment]
Okay so we've closed up registrations and final count is in. We had 31 people that passed wave 2 but didn't get in. 5 of them were due to the quota.

**Comment by PedroGFonseca** [comment]
What... a... night. Great job Mr. Sam :)

**Comment by HelderJorge** [comment]
Hello. Sorry to come in. I just navigated to this issue. 31 people that passed are out! I´m really scared. I really want to get in. When will we know our status?

**Comment by hershaw** [comment]
Just a quick announcement: there were a total of 81 successful tests, and only 50 spots. This means that whether those tests got in are dependent on the timestamp and the quota.

If you are not in the top 50, it does not yet mean you are out, but you may be dependent on someone in the top 50 not taking up their spot (which does happen). It is the first time we've been this oversubscribed, and I wish we could take everyone, however to ensure that the quality is high for the students we cannot change the class size.

Everyone will get an email with their situation very soon, independently of whether or not they are in at this point.
