### ISSUE TITLE
Ad-hoc academy

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#26]
dear academy peeps,

We have 31 people that qualified but won't be able to make it into the Academy. That's enough for a community. I'm wondering if we can get a group of 3 or 4 of them to organize a sidecar academy where they use the open-source material and just run as similar-as-possible course that lags behind a month or so from batch3.

Right now there are so many people that want in and aren't gonna get the chance to learn what we have to teach. It's kind of breaking my heart. We should figure something out to help.

A ~~penny~~ golden dragon for your thoughts?

**Comment by PedroGFonseca** [comment]
My 2 ~cents~ ~dragons~ lizards: 

We are going to be stretched close to capacity, but it would indeed be cool to have them self-organize. 

Suggested: 
1. We try to get someone from last year's alumni to take this up
2. A few applicants take the initiative of managing this day to day  (we can live stream the talks maybe?) 
3. We invite them to the community events, but don't do much more than that

This may sound cold, but I think we have an obligation to the students that is not trivial to meet, and anything that may distract from that would be risky.

**Comment by hershaw** [comment]
agreed, we don't have any additional resources to spend on this. they would have to do it themselves.

Why someone from last year alum and not someone from the group that just applied? would probably be a lot easier to recruit from there and stay involved.

**Comment by PedroGFonseca** [comment]
The logic for the alumni is just that they've gone through it, so would make better "informal instructors"

**Comment by hershaw** [comment]
I've spoken to a few of the students that didn't get in so far. I have one, possibly two so far that are interested in organizing an ad-hoc academy. more news as soon as I have it.

**Comment by hershaw** [comment]
After this happens, I'll try to reach out to some Alum from batch2.

**Comment by hershaw** [comment]
So this didn't happen. bummer sauce, we'll work on it for next time.

**Comment by PedroGFonseca** [comment]
I think it's for the best. We need to make this excellent for the 50, and anything else needs to come from someone else (students self organising would be a dream)
