### ISSUE TITLE
Course-end hackathon and wrap-up event

### ISSUE THREAD

**Issue by ivopbernardo** [LDSSA/forum#28]
Hi everyone,

We are coming back to this idea lately but I would like to discuss it with everyone. What do you think of doing a big course-end hackathon in February or March? Mainly this would consist of a hackathon with teams of graduates, teachers and partners (the ones that lent us the space during the academy) where we would get everyone together and wrapped-up the entire course.

Arguments for:
- Give one last chance for students to come together;
- Reward partners for their help;
- Wrap-up of the course;
- Beer!

Credits to Carol for shaping the idea.

**Comment by thecarolmartins** [comment]
This would be a great opportunity to (1) serve our mission; (2) make something different; (3) put students interaction with actual companies; (4) create and develop new relationships between the Academy and companies.

I believe this event should be in "neutral ground" and needs pre-planning to understand the implications of creating such an event. I'm biased but I think is totally awesome and hugeeeeee!!!

**Comment by hershaw** [comment]
Fully support the idea! Will be a great way to tie everything together that's really fun!

**Comment by PedroGFonseca** [comment]
Absolutely all for it. This would actually be the perfect setting for the long-dreamed-of job fair :)

**Comment by ivopbernardo** [comment]
Awesome, I'll pitch it up to our partners on the next meetings. Thank you everyone!
