### ISSUE TITLE
Starters Academy Charter

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#3]
[Here is the charter.](https://docs.google.com/document/d/1kQSYyhxYkYIxTXOb2PbQF8qZfGikFzy_nypathWPJ5E/edit?usp=sharing)

Since the parent organization enables charters to be written for courses, we will use our first course which is the Starters Academy that we all know and love as the first one.

The parent organization charter is [here](https://docs.google.com/document/d/1EDQF8lFZA0DYKhru57rxLI4d7s3ReiN90BFdjTHtP-Q/edit?usp=sharing).

**Comment by hershaw** [comment]
This is a test, will it generate a notification?

**Comment by PedroGFonseca** [comment]
I suggest we close this as an issue, or give it a max time for comments
