### ISSUE TITLE
Bootcamp Schedule

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#32]
# Batch3 Bootcamp Schedule

Here's the schedule. Anyone see any issues with it?

## Saturday (July 6th)

- 8h00 - arrival, breakfast, student setup
- 8h45 - welcome, kickoff, meet the team- Sam Hopkins
- 9h00 - SLU01 - Pandas 101
- 10h00 - SLU02 - Subsetting Data in Pandas
- 11h00 - SLU03 - Visualization with Pandas and Matplotlib 
- 12h00 - Lunch
- 13h00 - SLU04 - Basic Stats with Pandas
- 14h00 - SLU05 - Covariance and Correlation 
- 15h00 - Coffee break
- 15h15 - SLU06 - Dealing with Data Problems 
- 16h15 - SLU07 - Regression with Linear Regression
- 17h15 - Coffee break
- 17h30 - SLU08 - Classification with Logistic Regression
- 18h30 - SLU09 - Model Selection and Overfitting
- 19h30 - Closing Remarks
- 20h00 - Change Venue for Networking and Beers

## Sunday (July 7th)
- 8h00 - arrival, breakfast, student setup
- 8h30 - SLU10 - Metrics for Regression 
- 9h30 - SLU11 - Metrics for Classification
- 10h30 - Coffee break
- 10h45 - SLU12 - Support Vector Machines
- 11h45 - SLU13 - Tree-Based Models
- 12h45 - Lunch
- 13h45 - SLU14 - k-Nearest Neighbors
- 14h45 - SLU15 - Feature Engineering
- 15h45 - Coffee break
- 16h00 - SLU16 - Data Sufficiency and Selection
- 17h00 - SLU17 - Ethics and Fairness
- 19h00 - Closing Remarks
- 20h00 - Change Venue for Networking and Beers

## Sunday (July 21st)
- 8h00 - Arrival, Breakfast, Student setup
- 8h30 - SLU18 - Hyperparameter Tuning
- 9h30 - SLU19 - Workflow
- 10h30 - Hackathon Prompt, Team Assignment
- 10h45 - Start hacking!
- 13h00 - Lunch Served (no need to stop hacking)
- 14h00 - Goal - make first submission
- 15h00 - Goal - make improved submission
- 16h00 - Start Working on Presentation
- 17h00 - Stop Hacking!
- 17h30 - Team Presentations
- 18h30 - Winners Announced
- 18h45 - Beers and Networking
- 20h00 - Building Closed / Move Party Elsewhere

**Comment by hershaw** [comment]
Added this to the wiki so I'll close the issue for now

**Comment by PedroGFonseca** [comment]
Pretty perfect! Couple of quick suggestions: 

1. shall we do `8h45 - welcome, kickoff, meet the team- Sam Hopkins` at 8:30? That would leave a bit of a cushion and help the SLUs start on time. 

2. Also maybe having a bathroom break at 11h00, making SLU03 start at 11:10, and lunch at 12:10?

**Comment by hershaw** [comment]
1. I wanted to have extra time before the official start in case there are some snafus with people getting into the building / getting setup and comfortable. what do you think of the reasoning?
2. I think that since they have kind of defacto bathroom breaks during each SLU because 45 minutes of it is do whatever you want that it won't be necessary. plus everyone will have full energy from it being the first hours of the first day and it's already difficult to get all of the SLUs fit in. again, what do you think of the reasoning?
