### ISSUE TITLE
Batch4 Boot Camp Operations

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#34]
If I'm missing anything, leave a comment and let me know!

## What

This is meant to discuss a plan of action for pulling off the bootcamp on July 18th and 19th, 2020.

### Get everyone on Slack

- Once on slack distribute the batch4-students repo and ask them to do the setup

### Make the welcome presentation

And update the batch4-students repo.

### Make the the schedule

Should be on a google calendar

### Make the presentation infrastructure

Options:

- Single Zoom room that is passed to the instructors giving the presentations
- Slidio?

### Do a test run

Whatever we come up with, we should do the equivalent of a power and internet check a few days before where someone opens an SLU and does the work.

**Comment by CatarinaSilva** [comment]
I'm taking care of slido events, just need the final dates of all SLUs

**Comment by PedroGFonseca** [comment]
CLOSE ALL THE THINGS!
