### ISSUE TITLE
Bootcamp Presentation Format

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#35]
So I'm thinking that we can have a single zoom room where we give the presentations. Something else that would allow for questions would also be great as well (slido?)

And then for rooms that require smaller numbers (like 5-10 people) we can use google meet. We can encourage instructors AND students to use the video conferencing tech that's most accessible to them. But if instructors are doing some Q&A, we'll need a process for that. I'm thinking the following:

- Every "instructor sponsored" room must have an instructor in it and present to allow people in
- They will pin the link to the slack channel while they are in it
- They will unpin the link to the slack channel when they leave
- Instructors should stay in their sponsored room as much as possible in order to monitor but if you have to leave early, that's okay. Just keep in mind that you won't be able to allow people back in so that meeting link will not be useful any more

Thoughts?

**Comment by minhhoang1023** [comment]
Zoom has a very nice feature that would allow us to create side-meetings ([breakout rooms](https://support.zoom.us/hc/en-us/articles/206476313-Managing-breakout-rooms#:~:text=Participants%20in%20breakout%20rooms%20can,room%20to%20join%20the%20room.)). I believe the instructor-sponsored room would fit nicely under this feature. Hangout would work fine too, but with this, everything will happen in Zoom so we could avoid moving across platforms and having multiple links.

We could:
1. Create in advance a specific Breakout room for each instructor: Something like SLU9 Room, SLU8 Room, etc.
2. Announce a message to all students that they could join breakout zoom. Students can choose to join or stay in the main room

![image](https://user-images.githubusercontent.com/40023817/87354357-5c065680-c556-11ea-8744-27123bcc15d3.png)

3. Allow students to go back to the main room once they finished asking questions

Happy to do a quick test on this!

**Comment by hershaw** [comment]
![image](https://user-images.githubusercontent.com/424192/87438593-a552b680-c5e7-11ea-8b09-4091a700832d.png)

ah it looks like we'd have to manually assign people to the breakout rooms - I don't think that people can just join and leave at will.

**Comment by minhhoang1023** [comment]
I thought the same at first! But in one support article, it mentioned that we could broadcast a message telling everyone that they could join the Breakout room.

![image](https://user-images.githubusercontent.com/40023817/87440607-11ceb500-c5ea-11ea-904b-3427826d60da.png)

**Comment by hershaw** [comment]
if this works, that would be great! I'm going to pay for Zoom and get it all set up for an experiment. This would be so great if it works!

**Comment by minhhoang1023** [comment]
I know right! If it works, I seriously will need to buy some Zoom stocks for its awesomeness

**Comment by hershaw** [comment]
okay Ivo and I just did a test and it looks like the breakout rooms don't work quite like that :-( You can't go in and out of them at will, you get assigned to one and that's the only one you have access to.

So I'm thinking that we actually just use hangouts. We can have just a single hangout that is the "lobby" and we leave hangout links on each of the calendar events where people can go to discuss the ones that they are working on. Furthermore they can always go back to them throughout the bootcamp and until the first hackathon. That way for the main event we have a single common place that we give all the presentations from and dedicated links for each of the events, including things like coffee breaks. This way, you can have the following experiences:

## Option 1: Stay in the main room the whole time

You won't miss anything. You leave it on, start paying attention when you hear something, and mostly work by yourself. Maybe you do a 1-on-1 with someone else but your experience is mostly slack and tuning into the presentations.

## Option 2: Be super social

Actively go to the room that is the subject of the hour. In this way you have more of a sensation of moving in and out of physical places. You are more likely to be in a room with less people and therefore more likely to meet others. Since there are different people entering and leaving at different paces, you always have a chance to hear or see something different.

## Conclusion

If we choose a format like this, we will stick to using one presentation technology and give people a few different options of experiences they can have. We can always adjust after the first day in the case it doesn't work.

Unsolved issue: someone must be present with a lisbondatascience.org email address in order to get into a room. From that point on people who don't have one will always be able to get in as long as there is one other person in the room. Not sure exactly how to solve this but I'm pretty sure we can figure out a way.

**Comment by minhhoang1023** [comment]
Sounds good!

For the unsolved issue, not ideal, but I could log in all the rooms in advance and just stay idle there. Or there needs to be someone actively admits people?

**Comment by PedroGFonseca** [comment]
Cleaning up, if there are any unclosed parts to this please feel free to re-open
