### ISSUE TITLE
AOR Lead positions to be filled

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#4]
On [this spreadsheet](https://docs.google.com/spreadsheets/d/1J40KycBTqoSra2o8jG2bzOYpfeYMswPvD73O8hzh7G0/edit#gid=559554334) we have a list of [Areas of Responsibility](https://github.com/LDSSA/wiki/wiki/LDSA-Areas-of-Responsibility) that need to be filled. 

If anyone is interested in any of them, DM me!

If you know anyone that is interested in any of them, send them to me! They only ask is that they be qualified for the particular position, whatever it may be. Don't be shy selling it, we're happy to work with anyone that wants to work with us!

**Comment by hershaw** [comment]
Just a quick update, we've got all the positions filled except for one! Now that the positions are filled, we can focus on the fun part: making shit happen!

I'll be in touch with each of the primary enablers for each AOR to make up a document and schedule a meeting to get our tasks set.

Really excited about how the team is shaping up! We should all be super proud!

**Comment by PedroGFonseca** [comment]
Update: still working on chasing Tesoureiro. Not forgotten, just hard. 

If anyone has leads, they are very welcome!
