### ISSUE TITLE
Batch 3 Dates

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#6]
## Proposal

Everything below is a proposal and will be finalized by Friday the 22nd of February at the very latest. 

## Most Important Dates

- Saturday, May 4th Wave 1 applications open
- Saturday July 6th the bootcamp will start

### Applications

The application process and dates are as follows: 

1. May 4th, 09 AM (Saturday):
    - First wave of applications starts and you receive a python challenge   
1. May 10th, 11 PM (Friday):
    - First wave ends, all tests need to be submitted by midnight   
1. May 11th - 12th @11 PM (Sunday):
    - Payment for the first wave
1. May 13th, 09 AM (Monday):
    - Second wave of applications starts and you receive a python challenge
1. May 19th, 11 PM (Sunday):
    - Second wave ends, all tests need to be submitted by midnight
1. May 20th - May 22nd 11 PM (Wednesday):
    - Payments for the second wave

Here's a visual aid:

![image](https://user-images.githubusercontent.com/424192/53697918-208a4280-3dce-11e9-95a6-e17690648d5a.png)

### Bootcamp

The bootcamp this year will be a different format. Since we do not have a 3-day weekend at the beginning of July and we had the feeling that the 3-day bootcamp last year was a bit too intense, we are going to split the 3 days of bootcamp over 2 weekends as follows:

- July 6th and 7th we will do bootcamp SLUs
- July 21st - the first hackathon and maybe a last SLU or two

Any communications about the bootcamp should make it clear that the entire time span of the 6th-21st will be intense and should be taken very seriously. We won't require physical presence of anyone on any work days nor will we expect anybody to take days off but it should be very clear that this portion of the academy will be intensive and should be carefully planned for.

If this goes as planned, we should be able to offer everyone a chance to finish the SLUs before we start hitting them hard with the BLUs and specializations.

Here's a visual aid:

![image](https://user-images.githubusercontent.com/424192/53697937-4ca5c380-3dce-11e9-939d-c2869c3e1c67.png)

## When communicating using these dates

The short term dates - the application schedule and the bootcamp we can be confident when talking about. 

The longer term dates- events that further away are more subject to change. We will obviously do everything that we can to keep them the same but things may arise.

## Feedback is welcome!

If anybody has any feedback on these dates or this plan, please let us know! We need to catch scheduling mistakes before they happen.

**Comment by PedroGFonseca** [comment]
Seems tight, but doable. Would be curious to see the opinion of more peeps on this one.

**Comment by manuelfcreis** [comment]
I feel like it's a good starting date, my only issue with it would be the final months which need some considerations.

Starting in July the final project would end up in December / January which is a particularly tricky time for a lot of people because of Xmas and School exams.

**Comment by dominguezmaria** [comment]
> I feel like it's a good starting date, my only issue with it would be the final months which need some considerations.
> 
> Starting in July the final project would end up in December / January which is a particularly tricky time for a lot of people because of Xmas and School exams.

The idea was to give students December free and have the capstone project during January, so in the end the academy would last 7 months instead of 6.
@hershaw do we have this info somewhere?

**Comment by hershaw** [comment]
Yeah it was supposed to provide some flexibility. It's about one month of work and so allowing students 2 months to do it was supposed to help them plan around it since they are busy months. 

That way if you are a student, then you can do most of the work in december and leave january to focus. Or if you would prefer to take december off and do just family stuff you can do so. Or if you are busy with both during December and January you have 8 full weeks to spread stuff out when you've got time.

Another thing here is that... there just isn't much other choice. I agree that it's not idea but was unable to come up with an alternative. So if a better idea presents itself, I'm 100% in!
