### ISSUE TITLE
Website broken on curriculum link

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#8]
When we click on the image in [curriculum](http://www.lisbondatascience.org/curriculum/), we end up on a broken link.

**Comment by PedroGFonseca** [comment]
I can fix this one, just wanted to have this bug noted somewhere. Wrong place?

**Comment by hershaw** [comment]
Okay to be here right now, soon we should create another repo to take care of it.

BTW I think I've found someone to take the communications AOR with managing the website being part of it.

**Comment by PedroGFonseca** [comment]
Sweet, who is it? The Unbounce account is still mine, so I'll have to share account details with her/him

**Comment by hershaw** [comment]
I've made an intro to them on slack :)

**Comment by PedroGFonseca** [comment]
Fixed, thanks!
