### ISSUE TITLE
Gender balance initiative: what actions should we be taking now? 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#9]
We’re launching the new Academy, and in order to [avoid the quotas](https://docs.google.com/document/d/1TmltrjS6Dts8qF8EuyVoCZHLrGr8mJTQsyL2RxkfDxE/edit) must now be clever about how we organically balance the applications. 

I’ve done a couple of super basic things: reached out to some of the meetups and asked to speak at the end (especially women in tech, etc), and asked specifically for people to tag women on my linkedin post. 

This is hardly even a start, however. What should we be doing?

**Comment by PedroGFonseca** [comment]
Ideas: 

a) launching an event of the Python meetup and/or Lisbon Data Science Meetup. This would have to have at least 50% women (or defeats the purpose), I believe we can do that by controlling the queues. 

b) targeting a Google Ads campaign as women who know python. Not sure how much this would cost. 

c) asking startup Lx to communicate the Academy in the newsletter, targeting the message specifically at women 

d) asking to do talks at universities which aren't engineering schools 

e) creating a "buddy system" in which each instructor agrees to chase and persuade at least 3 women to join 

f) going through the mailchimp emails, inferring which ones are women and targeting a specific message at that group

**Comment by carol-Martins** [comment]
Those are great ideas!

We (#marketing) had the idea for segmenting the mailing list + direct FB Ads for Women.

To achieve the quota - for the first wave - we have done the math to how many women we need on the mailing list. I need to check and I’ll write it here ASAP.

**Comment by adleite** [comment]
Great work Pedro, should we make a campaign (some facebook posts) where we advertise the success of women that are linked to LDSA?

**Comment by PedroGFonseca** [comment]
All for it, the issue is that whenever we post on facebook / linkedin etc we reach a lot more dudes than dudettes, so it is not a great way to undo the balance. But promoting women in the Academy context is always a good idea.

**Comment by carol-Martins** [comment]
Jose Medeiros is working on proposing a fb/IG Ads campaign target to women. We do believe that it’s important. 

Here is the data/insights we’ve gathered from the previous batch to achieve the quota:

If we want 50 students on the first wave, considering that all of them convert from the subscribers list we need (with the same behavior of batch 2 as Jose+me researched) we would need an additional of +1.268 subscribers to our actual list. 

Breaking down the numbers considering last year conversion rates that we need for this batch:
- 398 applicants 
- which 65 will have a score of 6 on the test
- 50 will pay
- for the whole process we want 86 women to meet the 16% rate

**Comment by PedroGFonseca** [comment]
Turned this into a Trello Board: https://trello.com/b/3RpihgI0/gender-equality-initiative

Please comment on each card to work on them. LET'S DO THIS THAING!

**Comment by carol-Martins** [comment]
Hey Pedro,

I don’t have permission to see the board.

Enviado do meu iPhone

No dia 09/03/2019, às 18:18, Pedro Fonseca <notifications@github.com> escreveu:

**Comment by PedroGFonseca** [comment]
@carol-Martins that's odd, it belongs to the LDSA org, are you logged in?
